### ISSUE TITLE
关于软件功能的疑惑

### ISSUE THREAD

**Issue by BugTD** [ToKiNoBug/SlopeCraftTutorial#3]
请问什么时候可以支持<h2>1.19版本呢？</h2>
傻瓜式教程打不开了？
<h2>帮助教程是.tex格式，可以转成.md吗？</h2>

**Comment by ToKiNoBug** [comment]
1.19正式版还没出呢，新方块对应的地图特性也还没稳定下来，着哪门子急啊。

**Comment by ToKiNoBug** [comment]
帮助教程用latex写就是为了编译成pdf（latex练手），你直接看压缩包里附带的pdf就行了，转markdown就等于重新排版，我不想这么做。

**Comment by ToKiNoBug** [comment]
我这边看到v3.0和v3.1的教程都能正常查看啊，你仔细描述一下傻瓜式教程打不开的具体现象？
